Expanded participant section
decentralized-identity/credential-trust-establishment pull request #36
Opened 2024-02-26 17:55 UTC by TelegramSam

2024-02-26 18:25 UTC, mccown commented
This is a good PR.  I like the new organization / formatting.

2024-02-26 18:25 UTC, TelegramSam commented
Fixes #34 
Fixes #35

2024-03-04 17:41 UTC, Eldersonar requested changes
Minor typos to fix

2024-03-04 17:41 UTC, Eldersonar commented on credential-trust-establishment/spec.md
> +Versioning is a way to allow users of decentralized ecosystem governance to track/use the current version of published governance or track/use older version of the file. This allowes flexibility of u
version of  DEGov file at any time should be version of the DEGov file at any time?

2024-03-04 17:41 UTC, Eldersonar commented on credential-trust-establishment/spec.md
> +This schema provides additional information for each identifier in the ecosystem. This is helpful for bootstrapping ecosystems without a reliable external system of participant identity. The folowing
"folowing" should be "following".

2024-03-04 19:34 UTC, Eldersonar requested changes
please, see more

2024-03-04 19:34 UTC, Eldersonar commented on credential-trust-establishment/spec.md
> +Linked governance allows for governance chains to exist - the inclusion of an external governance file allows that governance to itself reference other governance files. While in theory this allows f
"responsiblities" should be "responsibilities".

2024-03-04 19:34 UTC, Eldersonar commented on credential-trust-establishment/spec.md
> +## Participants
"univeristy" should be "university" in the section "Roles" section above

2024-03-04 19:34 UTC, Eldersonar commented on credential-trust-establishment/spec.md
> +Linked governance allows for governance chains to exist - the inclusion of an external governance file allows that governance to itself reference other governance files. While in theory this allows f
is linking correct? (Requirements of Ecosystem Participants)[#requirements-of-ecosystem-participants]

2024-03-06 23:32 UTC, Eldersonar approved these changes
Thank you, looks good!

2024-03-06 23:33 UTC, merged